name: Run Python Script Hourly

on:
  workflow_dispatch:        # Allows manual runs from the Actions tab
  schedule:
    - cron: '0 * * * *'     # Runs every hour (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
